dspace_core:
  build: .
  ports:
   - "8080:8080"
  env_file:
   - ./conf/database.conf
   - ./conf/dspace.conf
backup:
  extends: dspace_core
  volumes: 
   - ./data:/data_target
  command: 'bash "cp -r /data/* /data_target/"'
dspace:
  extends: dspace_core
  volumes: 
   - ./data:/data
