core:
  build: .
  env_file:
   - ./conf/database.conf
   - ./conf/dspace.conf
data:
  extends: core
  volumes: 
   - /data
   - /dbdata
  command: '/bin/true'
production:
  extends: core
  volumes_from: 
   - data
  ports:
   - "8080"
  restart: always
dev:
  extends: core
  volumes: 
   - ./data:/data
   - ./bin:/usr/local/bin
  ports:
   - "8080"
   - "8080:8080"
prepare_dev:
  extends: core
  volumes_from: 
   - data
  volumes: 
   - ./data:/data_target
  # - ./bin:/usr/local/bin
  command: 'volume.backup data'

