version: '2'
services:
  core: &core
    build: .
    env_file: &env_file
     - ./install/conf/env.conf
    command: dspace.run
  dspace:
    <<: *core
    depends_on:
     - db
    volumes_from: 
     - data
    ports:
     - "80:8080"
    restart: always
  shell:
    <<: *core
    depends_on:
     - db
    volumes_from: 
     - data
    working_dir: /working_dir
    volumes:
     - .:/working_dir
    command: bash
  db:
    image: postgres:9
    env_file: *env_file
  pgcli:
    image: mribeiro/pgcli
    depends_on:
     - db
    command: ["-h", "db", "-U", "postgres", "-d", "dspace"]
  data:
    <<: *core
    volumes: 
     - /data
     - /dbdata
    command: '/bin/true'
  prepare_with_data: &backup
    <<: *core
    volumes_from: 
     - data
    volumes: 
     - ./data:/data_target
    environment:
      DATA_TARGET: '/data_target'
    command: 'volume.backup data'
  with_data: &with_data
    <<: *core
    volumes: 
     - ./data:/data
    depends_on:
     - db
    ports:
     - "80:8080"
  rebuild: # docker-compose run --serivce-ports rebuild
    <<: *with_data
    volumes: 
     - ./data:/data
     - ./dspace-src:/outside_src
    environment:
      DSPACE_OUTSIDE_SOURCE_PATH: /outside_src
    command: 
     - bash
     - "-c"
     - 'dspace.rebuild "package -P !dspace-lni,!dspace-sword,!dspace-swordv2,!dspace-xmlui" && dspace.run'
  # TODO: AIP import and export
  backup: # actually useless ...
    <<: *backup
    command: 'volume.backup dbdata'

