dspace:
  build: .
  ports:
   - "8080:8080"
  volumes:
   - .:/deploy
  volumes_from:
   - db
  links:
   - db
  environment:
    POSTGRES_HOST: /var/run/postgres
  env_file:
   - ./postgres.conf
db:
  image: postgres 
  volumes:
   - /var/run/postgresql
  env_file:
   - ./postgres.conf
